workflows:
  privatecloud-ios:
    name: PrivateCloud iOS
    max_build_duration: 45
    instance_type: mac_mini_m2
    environment:
      groups:
        - ymnknet
      vars:
        XCODE_PROJECT: "Nextcloud.xcodeproj"
        XCODE_SCHEME: "Nextcloud"
        APP_STORE_CONNECT_KEY_IDENTIFIER: 82H5J855MP
        APP_STORE_CONNECT_ISSUER_ID: 5cb3a482-8441-442e-a748-62ef51dc132d
        BUNDLE_ID: "com.ymnknet.privatecloud"
      xcode: latest
    scripts:
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --platform IOS \
            --type IOS_APP_ADHOC \
            --create
          app-store-connect fetch-signing-files "$BUNDLE_ID.*" \
            --platform IOS \
            --type IOS_APP_ADHOC \
            --create
      - name: Set up keychain and profiles
        script: |
          keychain initialize
          app-store-connect list-certificates \
            --type IOS_DISTRIBUTION \
            --save
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
